/* 
 * AdOut.Planning API
 *
 * Access to Apps API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = AdOut.Stream.Planning.Client.Client.SwaggerDateConverter;

namespace AdOut.Stream.Planning.Client.Model
{
    /// <summary>
    /// Defines ScheduleType
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum ScheduleType
    {
        /// <summary>
        /// Enum Daily for value: Daily
        /// </summary>
        [EnumMember(Value = "Daily")]
        Daily = 0,
        /// <summary>
        /// Enum Weekly for value: Weekly
        /// </summary>
        [EnumMember(Value = "Weekly")]
        Weekly = 1,
        /// <summary>
        /// Enum Specific for value: Specific
        /// </summary>
        [EnumMember(Value = "Specific")]
        Specific = 2    }
}
