/* 
 * AdOut.Planning API
 *
 * Access to Apps API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = AdOut.Stream.Planning.Client.Client.SwaggerDateConverter;

namespace AdOut.Stream.Planning.Client.Model
{
    /// <summary>
    /// UpdateAdModel
    /// </summary>
    [DataContract]
        public partial class UpdateAdModel :  IEquatable<UpdateAdModel>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateAdModel" /> class.
        /// </summary>
        /// <param name="adId">adId.</param>
        /// <param name="title">title.</param>
        public UpdateAdModel(string adId = default(string), string title = default(string))
        {
            this.AdId = adId;
            this.Title = title;
        }
        
        /// <summary>
        /// Gets or Sets AdId
        /// </summary>
        [DataMember(Name="adId", EmitDefaultValue=false)]
        public string AdId { get; set; }

        /// <summary>
        /// Gets or Sets Title
        /// </summary>
        [DataMember(Name="title", EmitDefaultValue=false)]
        public string Title { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UpdateAdModel {\n");
            sb.Append("  AdId: ").Append(AdId).Append("\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as UpdateAdModel);
        }

        /// <summary>
        /// Returns true if UpdateAdModel instances are equal
        /// </summary>
        /// <param name="input">Instance of UpdateAdModel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UpdateAdModel input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.AdId == input.AdId ||
                    (this.AdId != null &&
                    this.AdId.Equals(input.AdId))
                ) && 
                (
                    this.Title == input.Title ||
                    (this.Title != null &&
                    this.Title.Equals(input.Title))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.AdId != null)
                    hashCode = hashCode * 59 + this.AdId.GetHashCode();
                if (this.Title != null)
                    hashCode = hashCode * 59 + this.Title.GetHashCode();
                return hashCode;
            }
        }
    }
}
